use_frameworks!

abstract_target 'Demo' do
  pod 'RealmSwift', '~> 10.5'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRealm'
  pod 'RxRealmDataSources', :path => '../'

  target 'RxRealmDataSources_Example' do
    platform :ios, '9.0'
  end

  target 'RxRealmDataSources_MacExample' do
    platform :osx, '10.12'
  end
end
